apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-worker-9239
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-worker-9239
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
